site_name: "[alunjam.es ~]$"
site_url: https://alunjam.es
site_description: This is my personal site where I share my thoughts, guides, projects, and discoveries
site_author: Alun
repo_url: https://github.com/aloonj/
repo_name: aloonj

theme:
  name: simple-blog
  custom_dir: overrides
  highlightjs: true
  theme_style: light
  sidebar: true
  navigation_depth: 3
  site_name_style: fw-bold
  components:
    title: false
    home_title: false
    page_title: false
    site_name: true
    footer: false

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/mobile-menu.js

nav:
  - /home: index.md
  - /usr/share/docs:
    - Broadband:
      - broadband/sky-fttp-opnsense.md
    - LLM/AI:
      - llm/running-llms-locally-with-vllm.md
    - Mobile & Tablets:
      - Tab P11 LineageOS Install: mobile-tablets/lenovo-tab-p11-lineageos-install.md
      - Tab P11 Stock Recovery: mobile-tablets/lenovo-tab-p11-stock-recovery.md
    - Virtualisation/Cloud:
      - cloudstack/nested-cloudstack-ansible.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition
  - md_in_html

# Set the directory for the built site
site_dir: site
